### ISSUE TITLE
The cookie popup is an issue ?

### ISSUE THREAD

**Issue by wadie** [nickirk/immo#3]
When attempting to send a message on wg-gesucht, I get the following error:

``` Message: element click intercepted: Element <button class="btn btn-info pull-right create_new_conversation" type="submit" tabindex="5">...</button> is not clickable at point (653, 569). Other element would receive the click: <p class="cookie-message">...</p>```

Maybe we should ignore their cookie popup so we're able to click on `create_new_conversation` ?

Full Traceback:
![Screenshot_2019-08-06 Default - Codeanywhere](https://user-images.githubusercontent.com/1206307/62542580-568b9100-b85c-11e9-8193-0db784429116.png)

**Comment by nickirk** [comment]
This is a new change on their website, due to the GDPR (general data protection regulation), one can just click the "Agree" or "Ok" button in a similar fashion like this

```python
submit_button1 = driver.find_element_by_xpath("//button[@data-ng-click='submit()' or contains(.,'Nachricht senden')]")
submit_button1.click()
```

Just have a look into the source code of the website and identify the button. 
Sorry, this is not a blackbox tool since the website constantly changes/adds new stuff. And I cannot follow their moves and modify the script accordingly. But it can be solved and I will be happy to offer technical support to you when you try to solve the problem. If you managed to solve it, please add a pull request to the repository. Once it runs, it really saves you a lot of time and effort.
